#!/bin/sh
########################################################################
#
# Description : Module auto-loading script
#
# Authors     : Zack Winkles
#
# Version     : 00.00
#
# Notes       : Taken from http://www.linuxfromscratch.org/lfs/view/6.5/scripts/apds05.html
#
########################################################################

# Assure that the kernel has module support.
[ -e /proc/ksyms -o -e /proc/modules ] || exit 0

case "${1}" in
    start)

        # Exit if there's no modules file or there are no
        # valid entries
        [ -r /etc/modules ] &&
            egrep -qv '^($|#)' /etc/modules ||
            exit 0

        echo -n "Loading modules:"

        # Only try to load modules if the user has actually given us
        # some modules to load.
        while read module args; do

            # Ignore comments and blank lines.
            case "$module" in
                ""|"#"*) continue ;;
            esac

            # Attempt to load the module, making
            # sure to pass any arguments provided.
            modprobe ${module} ${args} >/dev/null

            # Print the module name if successful,
            # otherwise take note.
            if [ $? -eq 0 ]; then
                echo -n " ${module}"
            else
                failedmod="${failedmod} ${module}"
            fi
        done < /etc/modules

        echo ""

        # Print a failure message with a list of any
        # modules that may have failed to load.
        if [ -n "${failedmod}" ]; then
            echo "Failed to load modules:${failedmod}"            
        else
            echo "OK"
        fi
        ;;
    *)
        echo "Usage: ${0} {start}"
        exit 1
        ;;
esac
