[alias]
test-drone = "test --target armv7-unknown-linux-gnueabihf"
build-drone = "build --target armv7-unknown-linux-gnueabihf"
run-drone = "run  --target armv7-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-gnueabihf]
runner = ".cargo/runner.sh"
